# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'JuniorMathFac' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'SnapKit'
	pod 'Alamofire'
  # Pods for JuniorMathFac

end
